version: "3.7"
services:
    app:
        build:
            context: ./docker
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
        networks:
            - main
    mysql:
        image: mysql:8
        volumes:
            - mysql_data:/var/lib/mysql
            - ./docker:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: root
        networks:
            - main
    redis:
        image: redis:7
        volumes:
            - redis_data:/data
        networks:
            - main

volumes:
    mysql_data:
    redis_data:
networks:
  main:
    driver: bridge